### ISSUE TITLE
Nullreference exception in performSceneSwitchIfNecessary

### ISSUE THREAD

**Issue by Th0rstenf** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#36]
In second testing, there was a crash of SB, afterwards in ran smoothly. Log file reveals:

2023-02-14 18:43:40.633 ERR] InlineCode :: There was an error running the instance for ''
System.NullReferenceException: Object reference not set to an instance of an object.
   at m272ff561f834b9c935a1e42df9d1b07.CPHInline.performSceneSwitchIfNecessary()
   at m272ff561f834b9c935a1e42df9d1b07.CPHInline.Execute()
   at _YRlDUcVE1bvf08OmH7jUYD11W08._IrO7CWAdTiwFqM30RLaOFPK6YeY(Dictionary`2 , Boolean , String )
   at _YRlDUcVE1bvf08OmH7jUYD11W08._IrO7CWAdTiwFqM30RLaOFPK6YeY(Dictionary`2 , Boolean , String )
   at _J7OVFwXMqSkAqSPwWQc36kLKt3k._6siI3yfrb8okWWvb4XQZ6s5XTJx(Guid , _5TDDy9vOoKGcnuanNkkhHzNbQMDA , Dictionary`2 , Boolean , String , Boolean )
   at _S60XIRXsAhh050yDttxUXmk31th._WpMleZmDYAFkHmxhT3ntUAI6rPd.MoveNext()

**Comment by Th0rstenf** [comment]
Error could not be reproduced. A potential fix is implemented on the branch. Will be tested when the error can be reproduced.

As of now it might have been a weird side effect of another plugin. Can not reproduce locally so far.

**Comment by Th0rstenf** [comment]
I was still not able to reproduce it. This will be closed.
